import {
  SiJava as Java,
  SiJavascript as Javascript,
  SiHtml5 as Html,
  SiCss3 as Css,
  SiReact as React,
  SiAngular as Angular,
  SiNodeDotJs as Node,
  SiNextDotJs as Next,
  SiPython as Python,
  SiTypescript as Typescript,
  SiSass as Sass,
  SiVisualstudio as VisualStudio,
  SiPostgresql as Postgresql,
  SiOracle as Oracle,
  SiGit as Git,
  SiLinux as Linux,
} from 'react-icons/si';

export const icons = {
  Java,
  Javascript,
  Html,
  Css,
  React,
  Angular,
  Node,
  Next,
  Python,
  Typescript,
  Sass,
  VisualStudio,
  Postgresql,
  Oracle,
  Git,
  Linux,
};
